version: '3.1'
services:
    app:
      depends_on:
        - mongodb
        - mongo-express
        - redis
        - elasticsearch
      build: .
      ports:
        - 4455:4455

    mongodb: 
      image: mongo
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: p4ss

    mongo-express:
      image: mongo-express
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: p4ss
        ME_CONFIG_MONGODB_SERVER: mongodb
      depends_on:
        - "mongodb"
     
    redis:
      image: redis
      command: redis-server --requirepass redisp4ss
      ports:
        - 6379:6379

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=true
        - node.name=elasticsearch
        - ELASTIC_PASSWORD=elasticsearchP4ss
      ports:
        - "9200:9200"